core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("task_tracker.urls")),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

task_tracker/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from task_tracker import views
from task_tracker.views import CommentDeleteView, CommentUpdateView


app_name = "task_tracker"

urlpatterns = [
    path('', views.TaskListView.as_view(), name='task-list'),
    path('<int:pk>/', views.TaskDetailView.as_view(), name='task-detail'),
    path('<int:pk>/update', views.TaskUpdateView.as_view(), name='task-update'),
    path('<int:pk>/delete', views.TaskDeleteView.as_view(), name='task-delete'),
    path('task-create/', views.TaskCreateView.as_view(), name='task-create'),
    path('<int:pk>/complete/', views.TaskCompleteView.as_view(), name='task-complete'),
    path('login/', auth_views.LoginView.as_view(template_name='task_tracker/login.html'), name='login'),
    path('register/', views.register, name='register'),
    path('<int:pk>/edit/', CommentUpdateView.as_view(), name='comment-update'),
    path('<int:pk>/delete/', CommentDeleteView.as_view(), name='comment-delete'),


]

task_tracker/models.py
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    STATUS_CHOICES = [
        ("todo", "To do"),
        ("in_progress", "In progress"),
        ("done", "Done")
    ]
    PRIORITY_CHOICES = [
        ("low", "Low"),
        ("medium", "Medium"),
        ("high", "High")
    ]
    title = models.CharField(max_length=30)
    description = models.TextField()
    status = models.CharField(max_length=23, choices=STATUS_CHOICES, default="todo")
    priority = models.CharField(max_length=23, choices=PRIORITY_CHOICES, default="medium")
    due_date = models.DateField(blank=True, null=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="tasks")

    def __str__(self):
        return self.title

class Comment(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    media = models.FileField(upload_to = "comments_media/", blank = True,null=True)

    def __str__(self):
        return f"{self.task} - {self.author}"

task_tracker/forms.py
from django import forms
from task_tracker.models import Task, Comment

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["title", "description", "status", "priority", "due_date", "creator"]

    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({"class": "form-control"})
        self.fields["due_date"].widget.attrs["class"]+= " my-custom=datepicker"

class TaskFilterForm(forms.Form):
    STATUS_CHOICES = [
        ("", "All"),
        ("todo", "To do"),
        ("in_progress", "In progress"),
        ("done", "Done")
    ]
    status = forms.ChoiceField(choices=STATUS_CHOICES, required=False, label="status")

    def __init__(self, *args, **kwargs):
        super(TaskFilterForm, self).__init__(*args, **kwargs)
        self.fields["status"].widget.attrs.update({"class": "form-control"})


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content', 'media']
        widgets = {
            "media": forms.FileInput()
        }

task_tracker/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render, reverse, get_object_or_404, redirect
from django.urls import reverse_lazy
from task_tracker import models
from task_tracker.models import Comment
from django.views.generic import ListView, DetailView, CreateView, View, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from task_tracker.mixins import UserIsOwnerMixin
from task_tracker.forms import TaskForm, TaskFilterForm, CommentForm
from django.http import HttpResponseRedirect
from django.core.exceptions import PermissionDenied

class TaskListView(ListView):
    model = models.Task
    context_object_name = "tasks"
    template_name = "task_tracker/task_list.html"
    login_url = 'task_tracker/login.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        status = self.request.GET.get("status", "")
        if status:
            queryset = queryset.filter(status=status)
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = TaskFilterForm(self.request.GET)
        return context

class TaskDetailView(DetailView):
    model = models.Task
    context_object_name = "task"
    template_name = "task_tracker/task_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = self.object.comments.all()
        context['comment_form'] = CommentForm()
        return context
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.task = self.object
            comment.author = request.user
            comment.save()
            return redirect('task_tracker:task-detail', pk=self.object.pk)
        return self.render_to_response(self.get_context_data(comment_form = form))



class TaskCreateView(LoginRequiredMixin, CreateView):
    model = models.Task
    template_name = "task_tracker/task_form.html"
    form_class = TaskForm
    success_url = reverse_lazy("task_tracker:task-list")

    def form_valid(self,form):
        form.instance.creator = self.request.user
        return super().form_valid(form)

class TaskCompleteView(LoginRequiredMixin, UserIsOwnerMixin, View):
    def post(self, request, *args, **kwargs):
        task = self.get_object()
        task.status = "done"
        task.save()
        return HttpResponseRedirect(reverse_lazy("task_tracker:task-list"))
    
    def get_object(self):
        task_id = self.kwargs.get("pk")
        return get_object_or_404(models.Task, pk=task_id)
    

class TaskUpdateView(LoginRequiredMixin, UserIsOwnerMixin, UpdateView):
    model = models.Task
    form_class = TaskForm
    template_name = "task_tracker/task_update_form.html"
    success_url = reverse_lazy("task_tracker:task-list")

class TaskDeleteView(LoginRequiredMixin, UserIsOwnerMixin, DeleteView):
    model = models.Task
    success_url = reverse_lazy("task_tracker:task-list")
    template_name = "task_tracker/task_delete_confirmation.html"


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('task_tracker:task-list')
    else:
        form = UserCreationForm()
    return render(request, 'task_tracker/register.html', {'form': form})

class CommentUpdateView(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = "task_tracker/update_form.html"

    def get_success_url(self):
        return reverse_lazy('task_tracker:task-detail', kwargs={'pk': self.object.task.pk})

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author != request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['task'] = self.object.task
        return context


class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment
    template_name = "task_tracker/delete_form.html"

    def get_success_url(self):
        return reverse_lazy('task_tracker:task-detail', kwargs={'pk': self.object.task.pk})

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author != request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['task'] = self.object.task
        return context

templates/base.html
<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Task management system</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'task_tracker:task-list' %}">Main</a>
        <a class="navbar-brand" href="{% url 'task_tracker:login' %}">Login</a>
        <a class="navbar-brand" href="{% url 'task_tracker:register' %}">Register</a>
    </nav>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/task_tracker/delete_form.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h2>Сonfirm the deletion</h2>
  <p>Are you sure you want to delete this comment?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delte</button>
    <a href="{% url 'task_tracker:task-detail' task.pk %}" class="btn btn-secondary">Cansel</a>
  </form>
</div>
{% endblock %}

templates/task_tracker/login.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-3">
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-warning">Login</button>
    <button type="submit" class="btn btn-primaгу"><a href="{% url 'task_tracker:register' %}">Register</a></button>
  </form>
</div>
{% endblock %}

templates/task_tracker/register.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-3">
  <h2>Register</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class ="btn btn-warning">Register</button>
  </form>
</div>
{% endblock %}

templates/task_tracker/task_delete_confirmation.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <h2>Delete a task</h2>
    <p>Are you sure you want to delete the task? "{{ object.title }}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, delete</button>
        <a href="{% url 'task_tracker:task-list' %}" class="btn btn-secondary">No, back to the task list</a>
    </form>
</div>
{% endblock %}

templates/task_tracker/task_detail.html
{% extends 'base.html' %}

{% block content %}
{% load custom_tags %}
<div class="container mt-3">
    <h2>{{ task.title }}</h2>
    <p>Descriotion: {{ task.description }}</p>
    <p>Status: <span class="badge badge-primary">{{ task.status }}</span></p>
    <p>Priority: <span class="badge badge-secondary">{{ task.priority }}</span></p>
    <a href="{% url 'task_tracker:task-update' task.id %}" class="btn btn-warning">Edit</a>
    <a href="{% url 'task_tracker:task-delete' task.id %}" class="btn btn-danger">Delete</a>
    <h3>Comments</h3>
    <ul>
        {% for comment in comments %}
            <li>{{ comment.author }}</li>
            <li>{{ comment.created_at }}</li>
            <li>{{ comment.content }}</li>
            {% if comment.media %}
            <div class="comment-media">
                {% with comment.media.url as media_url %}
                    {% if media_url|slice:"-4:" == ".jpg" or media_url|slice:"-4:" == ".png" or media_url|slice:"-5:" == ".jpeg" %}
                        <img src="{{ media_url }}" alt="Изображение комментария" style="max-width: 1000px;">
                    {% elif media_url|slice:"-4:" == ".mp4" %}
                        <video width="320" height="240" controls>
                            <source src="{{ media_url }}" type="video/mp4">
                            Ваш браузер не поддерживает тег видео.
                        </video>
                    {% else %}
                        <a href="{{ media_url }}">Скачать файл</a>
                    {% endif %}
                {% endwith %}
            </div>
        {% endif %}        
            <li><a href="{% url 'task_tracker:comment-update' comment.pk %}" class="btn btn-warning">Edit</a>
            <a href="{% url 'task_tracker:comment-delete' comment.pk %}" class="btn btn-danger">Delete</a></li>

            <br>
        {% endfor %}
    </ul>
    <h3>Add comment</h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <button type="submit" class ="btn btn-warning">Submit</button>
    </form>
</div>
{% endblock %}

templates/task_tracker/task_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3">
    <h2>{{ view.title }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Save</button>
    </form>
</div>
{% endblock %}

templates/task_tracker/task_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-3">
    <h2>Task list</h2>
    <a href="{% url 'task_tracker:task-create' %}" class="btn btn-primary mb-3">Add task</a>
    
    <br>

    <form method="get" class="form-inline mb-3">
    {{ form.status.label_tag}}
    {{ form.status }}
    <button type="submit" class="btn btn-primary ml-2">Filter</button>
    </form>
    
    <ul class="list-group">
        {% for task in tasks %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <div>
                <a href="{% url 'task_tracker:task-detail' task.pk %}">{{ task.title }}</a>
                <span class="badge badge-primary">{{ task.status }}</span>
                <span class="badge badge-secondary">{{ task.priority }}</span>
            </div>
            <form action="{% url 'task_tracker:task-complete' task.pk %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-warning btn-sm">Mark as done</button>
            </form>
        </li>
        {% empty %}
        <li class="list-group-item">No tasks found.</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/task_tracker/task_update_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Edit task</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit" class="btn btn-primaгу">Edit task</button>
        <a href="{% url 'task_tracker:task-list' %}" class="btn btn-secondary">Back to task list</a>
    </form>
</div>
{% endblock %}

templates/task_tracker/update_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Update comment</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primaгу">Save changes</button>
        <a href="{% url 'task_tracker:task-detail' task.pk %} " class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}